version: '2'

services:
    postgis:
        image: "mdillon/postgis:9.6"
        volumes:
        - ./docker-data/postgis:/var/lib/postgresql/data
        environment:
            PGDATA: /var/lib/postgresql/data/PGDATA
    
    web:
        build: .
        expose:
        - "8000"
        links:
        - postgis:postgis
        command: "python /usr/src/app/manage.py runserver -d -r -p 8000 --host=0.0.0.0" # auto reload testing
        volumes:
        - .:/usr/src/app
        env_file:
        - ./common.env
    
    nginx:
        image: "nginx:alpine"
        volumes:
        - ./docker-data/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
        - "80:80"
        links:
        - web:web