apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sugarloaf-postgres
  labels:
    app: sugarloaf
    name: sugarloaf-postgres
    service: postgres
    tier: backend
spec:
  serviceName: "sugarloaf-postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: sugarloaf
        name: sugarloaf-postgres
        service: postgres
        tier: backend
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "restore",
                "image": "abkfenris/postgis-pghoard:9.6-1.4.0",
                "command": ["/bin/sh", "-c"], 
                "args": ["gosu postgres pghoard_restore get-basebackup --config /pghoard/pghoard.json --target-dir /var/lib/postgresql/data/pgdata --restore-to-master; sleep 1"],
                "volumeMounts": [
                    {
                        "name": "pg-data",
                        "mountPath": "/var/lib/postgresql/data/"
                    },
                    {
                        "name": "postgres-home",
                        "mountPath": "/home/postgres"
                    },
                    {
                        "name": "pghoard-config",
                        "mountPath": "/pghoard",
                        "readOnly": true
                    }
                ]
            }
        ]'
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pg-data
        emptyDir: {}
      - name: postgres-home
        emptyDir: {}
      - name: pghoard-config
        secret:
          secretName: sugarloaf-pghoard
      containers:
        - image:  abkfenris/postgis-pghoard:9.6-1.4.0
          name:  postgres
          ports:
          - containerPort: 5432
            name: postgres
            protocol: TCP
          lifecycle:
              preStop:
                  exec:
                      command: ["/bin/sh", "-c", "gosu postgres psql -c 'SELECT pg_switch_xlog();' && gosu postgres pg_ctl -d /var/lib/postgresql/data/pgdata -m fast -w stop"]
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 800m
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-home
              mountPath: /home/postgres
            - name: pghoard-config
              mountPath: /pghoard
              readOnly: true
          env:
          - name:  PGDATA
            value:  /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sugarloaf-secrets
                key: postgres-password
          - name: PGHOARD_USER
            valueFrom:
              secretKeyRef:
                name: sugarloaf-secrets
                key: pghoard-user
          - name: PGHOARD_PASS
            valueFrom:
              secretKeyRef:
                name: sugarloaf-secrets
                key: pghoard-pass
        - image: abkfenris/postgis-pghoard:9.6-1.4.0
          name: pghoard
          command: ["gosu", "postgres", "pghoard", "--config", "/pghoard/pghoard.json"]
          resources:
            requests:
              cpu: 10m
          volumeMounts:
          - name: pg-data
            mountPath: /var/lib/postgresql/data
          - name: postgres-home
            mountPath: /home/postgres
          - name: pghoard-config
            mountPath: /pghoard
            readOnly: true