apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sugarloaf-redis
  labels:
    name: sugarloaf-redis
    app: sugarloaf
    service: redis
    tier: backend
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: sugarloaf-redis
        app: sugarloaf
        service: redis
        tier: backend
    spec:
      containers:
      - image:  redis:3.2-alpine
        name: sugarloaf-redis
        resources:
          requests:
            cpu: "10m"
            memory: "10M"     
        ports:
        - containerPort:  6379
          name: redis
        imagePullPolicy: Always