"""Forgot a datetime for LiftStatus

Revision ID: 05a8e444ba31
Revises: 2bea2be77dcc
Create Date: 2016-12-01 12:02:31.300702

"""

# revision identifiers, used by Alembic.
revision = '05a8e444ba31'
down_revision = '2bea2be77dcc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lift_status', sa.Column('dt', sa.DateTime(), nullable=True))
    #op.drop_index('idx_lifts_geom', table_name='lifts')
    #op.drop_index('idx_trails_geom', table_name='trails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_lifts_geom', 'lifts', ['geom'], unique=False)
    op.drop_column('lift_status', 'dt')
    # ### end Alembic commands ###
