"""Forgot Lifts have names too

Revision ID: 2bea2be77dcc
Revises: c28cd6618f35
Create Date: 2016-11-30 21:07:00.085818

"""

# revision identifiers, used by Alembic.
revision = '2bea2be77dcc'
down_revision = 'c28cd6618f35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifts', sa.Column('name', sa.Text(), nullable=True))
    #op.drop_index('idx_lifts_geom', table_name='lifts')
    #op.drop_index('idx_trails_geom', table_name='trails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_lifts_geom', 'lifts', ['geom'], unique=False)
    op.drop_column('lifts', 'name')
    # ### end Alembic commands ###
