"""Add difficulty to Trail

Revision ID: 5e30dfb01774
Revises: 05a8e444ba31
Create Date: 2016-12-04 18:49:31.451864

"""

# revision identifiers, used by Alembic.
revision = '5e30dfb01774'
down_revision = '05a8e444ba31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('idx_lifts_geom', table_name='lifts')
    op.add_column('trails', sa.Column('difficulty', sa.Text(), nullable=True))
    #op.drop_index('idx_trails_geom', table_name='trails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    op.drop_column('trails', 'difficulty')
    #op.create_index('idx_lifts_geom', 'lifts', ['geom'], unique=False)
    # ### end Alembic commands ###
