"""Initial migration

Revision ID: c28cd6618f35
Revises: None
Create Date: 2016-11-30 00:43:31.083737

"""

# revision identifiers, used by Alembic.
revision = 'c28cd6618f35'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snow_reporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['snow_reporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lift_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=True),
    sa.Column('hold', sa.Boolean(), nullable=True),
    sa.Column('lift_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lift_id'], ['lifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('groomed', sa.Boolean(), nullable=True),
    sa.Column('snowmaking', sa.Boolean(), nullable=True),
    sa.Column('trail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trail_status')
    op.drop_table('trails')
    op.drop_table('lift_status')
    op.drop_table('daily_reports')
    op.drop_table('user')
    op.drop_table('snow_reporters')
    op.drop_table('lifts')
    op.drop_table('areas')
    # ### end Alembic commands ###
